version: '3.5'
services:
  app:
    build: .
    image: frankli0324/bilibili-download
    environment:
      - BILI_SESSDATA=
      - SECRET_KEY=
      - BILI_WORKDIR=/workdir
      - BILI_OUTDIR=/output
    volumes:
      - ./output:/output
      - ./workdir:/workdir
    ports:
      - 80:80
